version: "3"
services:
  nginx:
    container_name: ci3-auth-nginx
    image: nginx:latest
    volumes:
      - ./public:/public
      - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8001:80"
    restart: always
    networks:
      codeigniter_net:

  php:
    container_name: ci3-auth-php
    volumes:
      - ./public:/public
    build:
      context: ./public
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      codeigniter_net:

  database:
    platform: linux/amd64
    container_name: ci3-auth-mysql
    image: mysql:latest
    ports:
      - 3301:3306
    env_file:
      - .env
    networks:
      codeigniter_net:

  phpmyadmin:
    container_name: ci3-auth-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8011:80"
    env_file:
      - .env
    depends_on:
      - database
    networks:
      codeigniter_net:

networks:
  codeigniter_net:
